# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

desc "Print build info"
lane :print_build_info do
  version = get_version_number(target: "Hemlock")
  build = get_build_number()
  UI.message("version: #{version}")
  UI.message("build:   #{build}")
end

# TODO: implement same lanes as Android for major/minor/patch/build
desc "Increment build number"
lane :build do
  increment_build_number(
    skip_info_plist: true
  )
end
