# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

#-----------------------------------------
# funcs

def get_version_info(path = "../Hemlock.xcodeproj/project.pbxproj")
  content = File.read(path)

  m = content.match(/(MARKETING_VERSION = )(\d+)\.(\d+)\.(\d+);/)
  UI.user_error!("\"MARKETING_VERSION\" not found in #{path}") unless m

  major  = m[2]
  minor  = m[3]
  patch  = m[4]
  version = "#{major}.#{minor}.#{patch}"

  m = content.match(/(CURRENT_PROJECT_VERSION = )(\d+);/)
  UI.user_error!("\"CURRENT_PROJECT_VERSION\" not found in #{path}") unless m

  build = m[2]

  return version, build
end

#-----------------------------------------
# lanes

desc "Print version and build info"
lane :print_build_info do
  version = get_version_number(target: "Hemlock")
  build = get_build_number()
  UI.message("version: #{version}")
  UI.message("build:   #{build}")
end

desc "For one time use"
lane :set_version_explicitly do
  increment_version_number(version_number: "4.2.0")
  increment_build_number(build_number: "4")
end

lane :bump_version_major do
  increment_version_number(bump_type: "major")
  increment_build_number(build_number: "1")
end

lane :bump_version_minor do
  increment_version_number(bump_type: "minor")
  increment_build_number(build_number: "1")
end

lane :bump_version_patch do
  increment_version_number(bump_type: "patch")
  increment_build_number(build_number: "1")
end

lane :bump_version_build do
  increment_build_number()
end

lane :t do
  tag = "pines_4.2.0.4"
  msg = "4.2.0.4"
  if git_tag_exists(tag: tag, remote: true)
    UI.user_error!("tag already exists: #{tag}")
  end
  UI.message("tag: #{tag}")
  UI.message("msg: #{msg}")
end
